### ISSUE TITLE
Creating new user in admin backend throws exception

### ISSUE THREAD

**Issue by caveman99** [comlounge/camper#161]
Simply calling https://camper.local/users/admin/new results in this

Traceback (most recent call last):
  File "/home/thomas/lib/python2.7/site-packages/starflyer-2.1.1-py2.7.egg/starflyer/app.py", line 481, in __call__
    response = self.handle_exception(request, e)
  File "/home/thomas/lib/python2.7/site-packages/starflyer-2.1.1-py2.7.egg/starflyer/app.py", line 479, in __call__
    response = self.process_request(request)
  File "/home/thomas/lib/python2.7/site-packages/starflyer-2.1.1-py2.7.egg/starflyer/app.py", line 461, in process_request
    response = self.handle_user_exception(request, e)
  File "/home/thomas/lib/python2.7/site-packages/starflyer-2.1.1-py2.7.egg/starflyer/app.py", line 450, in process_request
    response = handler(**request.view_args)
  File "/home/thomas/lib/python2.7/site-packages/starflyer-2.1.1-py2.7.egg/starflyer/handler.py", line 227, in __call__
    rv = getattr(self, method)(**m)
  File "/home/thomas/lib/python2.7/site-packages/userbase-1.1.1-py2.7.egg/userbase/decorators.py", line 19, in wrapper
    return method(self, *args, **kwargs)
  File "/home/thomas/lib/python2.7/site-packages/userbase-1.1.1-py2.7.egg/userbase/decorators.py", line 54, in wrapper
    return method(self, *args, **kwargs)
  File "/home/thomas/lib/python2.7/site-packages/userbase-1.1.1-py2.7.egg/userbase/handlers/usereditor.py", line 92, in get
    form = cfg.add_form(self.request.form, module = self.module)
  File "/home/thomas/lib/python2.7/site-packages/WTForms-2.1-py2.7.egg/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/thomas/lib/python2.7/site-packages/userbase-1.1.1-py2.7.egg/userbase/handlers/forms.py", line 24, in __init__
    super(BaseForm, self).__init__(formdata=formdata, obj=obj, prefix=prefix, **kwargs)
  File "/home/thomas/lib/python2.7/site-packages/sf_babel-1.0.1-py2.7.egg/sfext/babel/wtformsupport.py", line 20, in __init__
    super(I18nForm, self).__init__(formdata=formdata, obj=obj, prefix=prefix, **kwargs)
  File "/home/thomas/lib/python2.7/site-packages/WTForms-2.1-py2.7.egg/wtforms/form.py", line 272, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "/home/thomas/lib/python2.7/site-packages/WTForms-2.1-py2.7.egg/wtforms/form.py", line 52, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "/home/thomas/lib/python2.7/site-packages/WTForms-2.1-py2.7.egg/wtforms/meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "/home/thomas/lib/python2.7/site-packages/WTForms-2.1-py2.7.egg/wtforms/fields/core.py", line 350, in bind
    return self.field_class(*self.args, **kw)
  File "/home/thomas/lib/python2.7/site-packages/userbase-1.1.1-py2.7.egg/userbase/handlers/forms.py", line 84, in __init__
    super(SelectMultipleField, self).__init__(label, validators, **kwargs)
  File "/home/thomas/lib/python2.7/site-packages/WTForms-2.1-py2.7.egg/wtforms/fields/core.py", line 446, in __init__
    super(SelectField, self).__init__(label, validators, **kwargs)
  File "/home/thomas/lib/python2.7/site-packages/WTForms-2.1-py2.7.egg/wtforms/fields/core.py", line 415, in __init__
    super(SelectFieldBase, self).__init__(label, validators, **kwargs)
  File "/home/thomas/lib/python2.7/site-packages/WTForms-2.1-py2.7.egg/wtforms/fields/core.py", line 95, in __init__
    raise TypeError("Must provide one of _form or _meta")
TypeError: Must provide one of _form or _meta

**Comment by mrtopf** [comment]
as said on twitter: the global admin interface is more of a remnant from camper 1.0 and I should probably remove it until I have time to fix it. The usual method would be to use the command line script or let people just register themselves (e.g. during registration).

**Comment by caveman99** [comment]
That assessment is correct, however the 'um' commandline tool seems to be broken too. For initital setup i had to register on the website and then find out how the 'username' is constructed from the fullname in the signup form (hint: lowercase and underscore instead of space). I then could successfully use the um command for privilege elevation.

[thomas@localhost ~]$ bin/um -f etc/scripts.ini add thomas thomas@localhost.localdomain meinpasswort
/home/thomas/lib/python2.7/site-packages/passlib-1.7.1-py2.7.egg/passlib/utils/handlers.py:1692: PasslibConfigWarning: The 'vary_rounds' option is deprecated as of Passlib 1.7, and will be removed in Passlib 2.0
Traceback (most recent call last):
  File "bin/um", line 11, in <module>
    load_entry_point('userbase', 'console_scripts', 'um')()
  File "/home/thomas/lib/python2.7/site-packages/userbase-1.1.1-py2.7.egg/userbase/scripts.py", line 51, in um
    mgr()
  File "/home/thomas/lib/python2.7/site-packages/userbase-1.1.1-py2.7.egg/userbase/scripts.py", line 32, in __call__
    user = m.users()
TypeError: __call__() takes exactly 2 arguments (1 given)
