### ISSUE TITLE
commenting on sessions sometimes gives an error. 

### ISSUE THREAD

**Issue by mrtopf** [comlounge/camper#95]
```
Traceback (most recent call last):
  File "/Users/cs/prj/camper/src/starflyer/starflyer/app.py", line 479, in __call__
    response = self.handle_exception(request, e)
  File "/Users/cs/prj/camper/src/starflyer/starflyer/app.py", line 477, in __call__
    response = self.process_request(request)
  File "/Users/cs/prj/camper/src/starflyer/starflyer/app.py", line 461, in process_request
    response = self.handle_user_exception(request, e)
  File "/Users/cs/prj/camper/src/starflyer/starflyer/app.py", line 450, in process_request
    response = handler(**request.view_args)
  File "/Users/cs/prj/camper/src/starflyer/starflyer/handler.py", line 227, in __call__
    rv = getattr(self, method)(**m)
  File "/Users/cs/prj/camper/src/camper/camper/base.py", line 337, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/cs/prj/camper/src/camper/camper/base.py", line 325, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/cs/prj/camper/src/starflyer/starflyer/decorators.py", line 72, in wrapper
    data = method(self, *args, **kwargs)
  File "/Users/cs/prj/camper/src/camper/camper/base.py", line 363, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/cs/prj/camper/src/camper/camper/barcamps/sessions.py", line 122, in delete
    comment = self.config.dbs.session_comments.get(cid)
  File "/Users/cs/prj/camper/src/mongogogo/mongogogo/record.py", line 260, in get
    raise ObjectNotFound(_id)
ObjectNotFound
```

**Comment by mrtopf** [comment]
I didn't really notice anything like that anymore, so closing it for now.
